services:

  redis:
    restart: always
    image: 'redis:5'
    ports:
      - '6379:6379'
    networks:
      - app-net

  backend:
    build: ./backend  
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
    networks:
      - app-net

  frontend:
    build: ./frontend  
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-net


networks:
  app-net:
    driver: bridge