export const MESSENGER_CHATS_REQUEST = "MESSENGER_CHATS_REQUEST";
export const MESSENGER_CHATS_SUCCESS = "MESSENGER_CHATS_SUCCESS";
export const MESSENGER_CHATS_FAIL = "MESSENGER_CHATS_FAIL";
export const MESSENGER_CHATS_CLEAR = "MESSENGER_CHATS_CLEAR";

export const MESSENGER_NOTIFICATIONS_REQUEST = "MESSENGER_NOTIFICATIONS_REQUEST";
export const MESSENGER_NOTIFICATIONS_SUCCESS = "MESSENGER_NOTIFICATIONS_SUCCESS";
export const MESSENGER_NOTIFICATIONS_FAIL = "MESSENGER_NOTIFICATIONS_FAIL";
export const MESSENGER_NOTIFICATIONS_CLEAR = "MESSENGER_NOTIFICATIONS_CLEAR";