export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_IN_STORAGE = 'USER_IN_STORAGE';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_CLEAR = 'USER_REGISTER_CLEAR';

export const USER_RESET_PASSWORD_EMAIL_REQUEST = 'USER_RESET_PASSWORD_EMAIL_REQUEST';
export const USER_RESET_PASSWORD_EMAIL_SUCCESS = 'USER_RESET_PASSWORD_EMAIL_SUCCESS';
export const USER_RESET_PASSWORD_EMAIL_FAIL = 'USER_RESET_PASSWORD_EMAIL_FAIL';

export const USER_RESET_PASSWORD_CHANGE_REQUEST = 'USER_RESET_PASSWORD_CHANGE_REQUEST';
export const USER_RESET_PASSWORD_CHANGE_SUCCESS = 'USER_RESET_PASSWORD_CHANGE_SUCCESS';
export const USER_RESET_PASSWORD_CHANGE_FAIL = 'USER_RESET_PASSWORD_CHANGE_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_IN_STORAGE = 'USER_PROFILE_IN_STORAGE';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_CLEAR = 'USER_UPDATE_CLEAR';

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL';
export const USER_PROFILE_UPDATE_CLEAR = 'USER_PROFILE_UPDATE_CLEAR';


